export enum MismatchedPassword {
  INVALID_CHARACTERS_LENGTH = 'INVALID_CHARACTERS_LENGTH',
  AT_LEAST_ONE_NUMBER = 'AT_LEAST_ONE_NUMBER',
  AT_LEAST_ONE_LOWERCASE = 'AT_LEAST_ONE_LOWERCASE',
  AT_LEAST_ONE_UPPERCASE = 'AT_LEAST_ONE_UPPERCASE',
  AT_LEAST_ONE_SPECIAL = 'AT_LEAST_ONE_SPECIAL',
}